name: Build WebStudio

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Скачуємо код репозиторію на CI
      - uses: actions/checkout@v3

      # Встановлюємо Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      # Встановлюємо залежності
      - run: npm install

      # Робимо збірку
      - run: npm run build
